services:
  db:
    image: postgres:15
    container_name: ans_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ans_password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: ans_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_URL=postgresql://postgres:ans_password@db:5432/postgres

  frontend:
    build:
      context: ./frontend
    container_name: ans_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend